import time
from selenium import webdriver
# 1 задание (Откройте http://practice.automationtesting.in/)
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
# 2 задание (Проскролльте страницу вниз на 600 пикселей)
driver.execute_script("window.scrollBy(0, 600);")
# 3 задание (Нажмите на название книги "Selenium Ruby" или на кнопку "READ MORE")
driver.find_element_by_css_selector("[title='Selenium Ruby']").click()
# 4 задание (Нажмите на название книги "Selenium Ruby" или на кнопку "READ MORE")
driver.find_element_by_xpath("//a[text()='Reviews (0)']").click()
# 5 задание (Поставьте 5 звёзд)
driver.find_element_by_class_name("star-5").click()
# 6 задание (Заполните поле "Review" сообщением: "Nice book!")
driver.find_element_by_id("comment").send_keys("Nice book!")
# 7 задание (Заполните поле "Name")
driver.find_element_by_id("author").send_keys("Sema")
# 8 задание (Заполните "Email")
driver.find_element_by_id("email").send_keys("sema841@mail.ru")
# 9 задание (Нажмите на кнопку "SUBMIT")
driver.find_element_by_id("submit").click()